### ISSUE TITLE
Expose component's bower.json for rewriting

### ISSUE THREAD

**Issue by MokoJumbie** [taptapship/wiredep#145]
It would be useful to have access to the values in each component's bower.json for use in the rewrite stage.

In my case, I would like to be able to do something in the config like:

```
fileTypes:
    html:
        replace:
            js: '<script type="text/javascript">window[{{bowerConfig.name}}] || document.write(\'<script src="js/vendor/{{filePath}}"><\/script>\');</script>'
```
